when:
  - event: push
    branch: custom
  - event: manual

steps:
  build-custom:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: registry.kcolb.com/ludx/hermes-agent
      registry: registry.kcolb.com
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      tags: custom
      dockerfile: Dockerfile.custom
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      event: [push, manual]

  #notify-dockhand:
  #  image: curlimages/curl:latest
  #  commands:
  #    - curl -X POST https://dockhand.kcolb.com/api/git/stacks/38/webhook
  #  when:
  #    event: push
  #    branch: main
  #  depends_on:
  #    - build-custom
